basic/urls.py
from django.urls import path
from .views import upload_photo, home, create_profile, profile, update, loginpage

urlpatterns = [
    path('upload_photo/', upload_photo, name='upload_photo'),
    path('home/', home, name='home'),
    path('login/', loginpage, name='login'),
    path('profile/<int:pk>', profile, name='profile'),
    path('update/<int:pk>', update, name='update'),
    path('create_profile/', create_profile, name='create_profile'),
]

criminaldbms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic.urls')),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

basic/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    folder_name = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    alias = models.CharField(max_length=100, null=True)
    gender = models.BooleanField()
    dob = models.DateField()
    POB = models.CharField(max_length=100, null=True)
    Nationality = models.CharField(max_length=100, null=True)
    body_marks = models.CharField(max_length=100, null=True)
    gang = models.CharField(max_length=100, null=True)
    wantedby = models.CharField(max_length=100)
    ctype = models.CharField(max_length=100)

    def __str__(self):
        return self.folder_name


class Charges(models.Model):
    p = models.ForeignKey(Profile, on_delete=models.CASCADE)
    wantedby = models.CharField(max_length=100)
    ctype = models.CharField(max_length=100)

basic/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['folder_name']

basic/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .forms import ProfileForm
from .models import Profile, User
import base64, cv2, os
import numpy as np
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout

def loginpage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Username or Password does not exist')
    context = {'page': page}
    return render(request, 'login.html', context)

def create_profile(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        alias = request.POST.get('alias')
        gender = request.POST.get('gender')
        dob = request.POST.get('date')
        pob = request.POST.get('pob')
        nation = request.POST.get('nation')
        gname = request.POST.get('gname')
        wby = request.POST.get('wby')
        ctype = request.POST.get('ctype')
        body_marks = request.POST.get('body_marks')
        folder_name = str(Profile.objects.all().count()+1)

        folder_path = os.path.join('static', 'profiles', folder_name)
        folder_path2 = os.path.join('static', 'pics', folder_name)
        os.makedirs(folder_path)
        os.makedirs(folder_path2)

        photo_data = request.POST['photo_data']
        img_data = base64.b64decode(photo_data.split(',')[1])

        nparr = np.frombuffer(img_data, np.uint8)
        img_np = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        cv2.imwrite('%s/%s.jpg' % (folder_path2, name), img_np)

        algo = os.path.join('static', 'haarcascade/haarcascade_frontalface_default.xml')
        haar_cascade = cv2.CascadeClassifier(algo)
        grayImg = cv2.cvtColor(img_np, cv2.COLOR_BGR2GRAY)
        face = haar_cascade.detectMultiScale(grayImg, 1.3, 4)
        if len(face) < 1:
            return redirect('create_profile')
        for (x, y, width, height) in face:
            faceOnly = grayImg[y:y + height, x:x + width]

        FACEONLY = np.ascontiguousarray(faceOnly)
        # Generate a unique filename for the image (you can use UUID or timestamp)
        filename = '0'
        filename2 = '1'
        cv2.imwrite('%s/%s.jpg' % (folder_path, filename), FACEONLY)
        cv2.imwrite('%s/%s.jpg' % (folder_path, filename2), FACEONLY)
        profile = Profile(folder_name=folder_name, name=name, alias=alias, gender=gender, dob=dob, POB=pob,
                          Nationality=nation, body_marks=body_marks, gang=gname, wantedby=wby, ctype=ctype).save()
        return render(request, 'success.html')  # Redirect to a success page

    return render(request, 'create_profile.html')


def upload_photo(request):
    if request.method == 'POST' and 'photo_data' in request.POST:
        photo_data = request.POST['photo_data']
        img_data = base64.b64decode(photo_data.split(',')[1])

        # Define the directory where images will be stored
        upload_dir = os.path.join('static', 'scanned_images')

        # Create the directory if it doesn't exist
        if not os.path.exists(upload_dir):
            os.makedirs(upload_dir)

        # Generate a unique filename for the image (you can use UUID or timestamp)
        filename = 'image.jpg'

        # Save the image to the upload directory
        with open(os.path.join(upload_dir, filename), 'wb') as f:
            f.write(img_data)

        # Construct the URL of the saved image
        image_url = os.path.join(upload_dir, filename).replace('\\', '/')

        haar_cascade = os.path.join('static', 'haarcascade/haarcascade_frontalface_default.xml')
        face_cascade = cv2.CascadeClassifier(haar_cascade)
        (images, labels, names, ids) = ([], [], {}, 0)
        (width, height) = (130, 100)
        count = 0
        dataset = os.path.join('static', 'profiles')
        # print('Training...')
        for (subdirs, dirs, files) in os.walk(dataset):
            for subdir in dirs:
                names[ids] = subdir
                subject_path = os.path.join(dataset, subdir)
                for filename in os.listdir(subject_path):
                    path = os.path.join(subject_path, filename)
                    label = ids
                    img = cv2.imread(path, 0)
                    img = cv2.resize(img, (width, height))
                    images.append(img)
                    labels.append(int(label))
                ids += 1

        # list the images and the labels
        (images, labels) = [np.array(img_list) for img_list in [images, labels]]

        # create a model of classifiers
        model = cv2.face.LBPHFaceRecognizer_create()
        # model = cv2.face.FisherFaceRecognizer_create()

        # train the model
        model.train(images, labels)
        nparr = np.frombuffer(img_data, np.uint8)
        img_np = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        grayImg = cv2.cvtColor(img_np, cv2.COLOR_BGR2GRAY)
        # obtain face coordinates
        faces = face_cascade.detectMultiScale(grayImg, 1.3, 5)
        predicted_names = []
        name = 'Unknown'
        for (x, y, w, h) in faces:
            face = grayImg[y:y + h, x:x + w]
            face_resize = cv2.resize(face, (width, height))
            prediction = model.predict(face_resize)
            # print(prediction)
            if prediction[1] < 800:
                name = names[prediction[0]]
            else:
                name = 'Unknown'
            predicted_names.append(name)
        queryset = Profile.objects.filter(folder_name__in=predicted_names)
        all_profiles = Profile.objects.all()
        remaining_profiles = all_profiles.difference(queryset)
        context = {
            'result': queryset,
            'others': remaining_profiles
        }
        return render(request, "result.html", context)

    else:
        return JsonResponse({'error': 'Failed to upload photo'}, status=400)


def home(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        alias = request.POST.get('alias')
        gender = request.POST.get('gender')
        dob = request.POST.get('date')
        pob = request.POST.get('pob')
        nation = request.POST.get('nation')
        gname = request.POST.get('gname')
        wby = request.POST.get('wby')
        ctype = request.POST.get('ctype')
        body_marks = request.POST.get('body_marks')
        folder_name = str(name) + str(dob)
        filters = Q()

        if name:
            filters &= Q(name__icontains=name)
        if alias:
            filters &= Q(alias__icontains=alias)
        if gender is not None:
            filters &= Q(gender=gender)
        if dob:
            filters &= Q(dob=dob)
        if pob:
            filters &= Q(POB__icontains=pob)
        if nation:
            filters &= Q(Nationality__icontains=nation)
        if gname:
            filters &= Q(gang__icontains=gname)
        if wby:
            filters &= Q(wantedby__icontains=wby)
        if ctype:
            filters &= Q(ctype__icontains=ctype)
        if body_marks:
            filters &= Q(body_marks__icontains=body_marks)

        # Filter profiles based on the constructed filter conditions
        queryset = Profile.objects.filter(filters)
        all_profiles = Profile.objects.all()
        remaining_profiles = all_profiles.difference(queryset)
        context = {
            'result': queryset,
            'others': remaining_profiles
        }
        return render(request, "result.html", context)
    return render(request, "home.html")

def profile(request,pk):
    if request.method == 'POST' and 'delete_profile' in request.POST:
        Profile.objects.get(id=pk).delete()
        return render(request, 'success.html')  # Redirect to a success page
    try:
        result=Profile.objects.get(id=pk)
    except Exception as e:
        return render(request, 'error.html')
    else:
        context={
        'result':result,
        }
        return render(request, "profile.html", context)

def update(request,pk):
    if request.method == 'POST':
        profile=Profile.objects.get(id=pk)
        name = request.POST.get('name')
        alias = request.POST.get('alias')
        gender = request.POST.get('gender')
        dob = request.POST.get('date')
        pob = request.POST.get('pob')
        nation = request.POST.get('nation')
        gname = request.POST.get('gname')
        wby = request.POST.get('wby')
        ctype = request.POST.get('ctype')
        body_marks = request.POST.get('body_marks')


        profile.name = name
        profile.alias = alias
        profile.gender = gender
        profile.dob = dob
        profile.POB = pob
        profile.Nationality = nation
        profile.body_marks = body_marks
        profile.gang = gname
        profile.wantedby = wby
        profile.ctype = ctype

        # Save the updated profile
        profile.save()
        return redirect('profile',pk)
    try:
        result = Profile.objects.get(id=pk)
    except Exception as e:
        return render(request, 'error.html')
    else:
        context = {
            'result': result,
        }
        return render(request, "update.html", context)

basic/templates/create_profile-old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Profile</title>
    <style>
        #video-container {
            margin: 20px auto;
            width: 400px;
        }

        #video {
            width: 100%;
            border: 2px solid black;
        }

        #capture-btn, #stop-btn, #start-btn {
            display: block;
            margin: 20px auto;
            padding: 10px 20px;
            font-size: 18px;
        }

        #photo-container {
            margin: 20px auto;
            width: 400px;
        }

        #photo {
            width: 100%;
        }
    </style>
</head>
<body>
<div id="video-container">
    <video id="video" autoplay></video>
</div>
<button id="capture-btn">Capture Photo</button>
<button id="stop-btn">Stop Camera</button>
<button id="start-btn">Start Camera</button>

<form id="upload-form" method="post" action="{% url 'create_profile' %}">
    {% csrf_token %}

    <label for="id_folder_name">Criminal File No.:</label>
        <input type="text" id="id_folder_name" name="folder_name" required maxlength="100">
        <br><br>

        <!-- Name Field -->
        <label for="id_name">Name:</label>
        <input type="text" id="id_name" name="name" required maxlength="100">
        <br><br>

        <!-- Gender Field -->
        <label for="id_gender">Gender:</label>
        <select id="id_gender" name="gender" required>
            <option value="1">Male</option>
            <option value="0">Female</option>
        </select>
        <br><br>

        <!-- Body Marks Field -->
        <label for="id_body_marks">Body Marks:</label>
        <input type="text" id="id_body_marks" name="body_marks" required maxlength="100">
        <br><br>

        <!-- Education Field -->
        <label for="id_education">Education:</label>
        <input type="text" id="id_education" name="education" required maxlength="100">
        <br><br>

        <label for="id_ctype">Criminal type:</label>
        <input type="text" id="id_ctype" name="ctype" required maxlength="100">
        <br><br>
    <input type="hidden" id="photo-data" name="photo_data">
    <button type="submit">Upload Photo</button>
</form>

<canvas id="canvas" style="display:none;"></canvas>
<div id="photo-container" style="display:none;">
    <img id="photo" alt="Captured Photo">
</div>

<script>
    const video = document.getElementById('video');
    const canvas = document.getElementById('canvas');
    const photo = document.getElementById('photo');
    const captureButton = document.getElementById('capture-btn');
    const stopButton = document.getElementById('stop-btn');
    const startButton = document.getElementById('start-btn');
    const photoDataInput = document.getElementById('photo-data');
    const photoContainer = document.getElementById('photo-container');
    let stream;
    let photosCaptured = 0;

    async function setupCamera() {
        try {
            stream = await navigator.mediaDevices.getUserMedia({video: true});
            video.srcObject = stream;
        } catch (err) {
            console.error("Error accessing webcam:", err);
        }
    }

    function capturePhoto() {
        // Set canvas dimensions to match video dimensions
        canvas.width = video.videoWidth;
        canvas.height = video.videoHeight;
        //const photo = new Image();
        const context = canvas.getContext('2d');
        context.drawImage(video, 0, 0, canvas.width, canvas.height);

        // Set photo dimensions to match canvas dimensions
        photo.width = canvas.width;
        photo.height = canvas.height;

        // Set photo src with canvas data
        photo.src = canvas.toDataURL('image/jpeg', 0.8); // Adjust quality here (0.8 is 80% quality)
        const photoData = canvas.toDataURL('image/jpeg', 0.8);
        photoDataInput.value = photoData;
        document.getElementById('photo-container').style.display = 'block';
        //photoContainer.appendChild(photo);
        //photosCaptured++;

        //if (photosCaptured < 10) {
        //    setTimeout(capturePhoto, 500); // Capture next photo after 500 milliseconds
        //} else {
        // Once all photos are captured, stop the camera
        //    stopCamera();
        //}
    }

    function stopCamera() {
        const tracks = stream.getTracks();
        tracks.forEach(track => track.stop());
        video.srcObject = null;
    }

    function startCamera() {
        setupCamera();
    }

    setupCamera();

    captureButton.addEventListener('click', capturePhoto);
    stopButton.addEventListener('click', stopCamera);
    startButton.addEventListener('click', startCamera);
</script>
</body>
</html>

basic/templates/create_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet"
          id="bootstrap-css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <title>Profile</title>
    <link rel="stylesheet" href="{% static 'css/cp.css' %}">
    <script>
        function openTab(evt, tabName) {
            var i, tabcontent, tablinks;

            // Hide all tab content
            tabcontent = document.getElementsByClassName("tab-pane fade");
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }

            // Remove the 'active' class from all tab buttons
            tablinks = document.getElementsByClassName("tablinks");
            for (i = 0; i < tablinks.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" active", "");
            }

            // Show the specific tab content
            document.getElementById(tabName).style.display = "block";
            document.getElementById(tabName).className += " show active";
            // Add the 'active' class to the button that opened the tab
            evt.currentTarget.className += " active";
        }

        // By default, open the first tab
        {#document.getElementById("defaultOpen").click();#}
    </script>
</head>

<body>
<div class="container emp-profile" style="border: 1px solid black;">
    <form id="upload-form" method="post" action="{% url 'create_profile' %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <video id="video" autoplay></video>
                    <div class="file btn btn-lg btn-primary" id="capture-btn">
                        Take Photo
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head" style="margin-top: 9%;">
                    <h5>
                        Phoenix
                    </h5>
                    <h6>
                        Your Trusted Criminal Record Resource
                    </h6>
                    <p class="proile-rating">RANKINGS : <span>8/10</span></p>
                    <div style="display: flex;">
                        <div>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" class="tablinks" onclick="openTab(event, 'tab1')"
                                       data-toggle="tab" role="tab" aria-controls="home"
                                       aria-selected="true">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" class="tablinks" onclick="openTab(event, 'tab2')"
                                       data-toggle="tab" role="tab" aria-controls="home"
                                       aria-selected="true">Criminal History</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" class="tablinks" onclick="openTab(event, 'tab3')"
                                       data-toggle="tab" role="tab" aria-controls="home"
                                       aria-selected="true">Other</a>
                                </li>
                            </ul>
                        </div>
                        <div style="margin-left: 22%;margin-right: 0;">
                            <input type="hidden" id="photo-data" name="photo_data">
                            <button type="submit"
                                    style="border: none;color: white;background-color: #007bff;padding: 4px 8px;border-radius: 5px;">
                                Add Profile
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <canvas id="canvas" width="320" height="240"></canvas>
                    <div class="file btn btn-lg btn-primary">
                        Captured Photo
                    </div>
                </div>
            </div>
            <div class="col-md-8" style="margin-top: 2%;">
                <div class="tab-content profile-tab">
                    <div class="tab-pane fade show active" id="tab1" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Name</label>
                            </div>
                            <div class="col-md-6" style="margin-left: -20%;">
                                <p><input type="text" placeholder="Name" name="name" required maxlength="100"> *</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Alias</label>
                            </div>
                            <div class="col-md-6" style="margin-left: -20%;">
                                <p><input type="text" name="alias" placeholder="Alias"></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Gender</label>
                            </div>
                            <div class="col-md-6" style="margin-left: -20%;">
                                <p><select placeholder="Gender" name="gender">
                                    <option value="1">Male</option>
                                    <option value="0">Female</option>
                                </select></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Date of Birth</label>
                            </div>
                            <div class="col-md-4" style="margin-left: -20%;">
                                <p><input type="date" name="date" placeholder="Date of Birth" required> *</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Place of Birth</label>
                            </div>
                            <div class="col-md-4" style="margin-left: -20%;">
                                <p><input type="text" name="pob" placeholder="Place of Birth"></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Nationality</label>
                            </div>
                            <div class="col-md-4" style="margin-left: -20%;">
                                <p><input type="text" name="nation" placeholder="Nationality"></p>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="tab2" role="tabpanel" aria-labelledby="crime-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Gang Name</label>
                            </div>
                            <div class="col-md-6" style="margin-left: -20%;">
                                <p><input type="text" placeholder="Gang Name" name="gname" maxlength="100"></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Wanted By</label>
                            </div>
                            <div class="col-md-6" style="margin-left: -20%;">
                                <p><input type="text" name="wby" placeholder="Department Name" required> *</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Criminal Category</label>
                            </div>
                            <div class="col-md-6" style="margin-left: -20%;">
                                <p><input type="text" name="ctype" placeholder="E.g. Murderer, Arsonist" required> *</p>
                            </div>
                        </div>
                    </div>
<div class="tab-pane fade" id="tab3" role="tabpanel" aria-labelledby="crime-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Body Marks</label>
                            </div>
                            <div class="col-md-6" style="margin-left: -20%;">
                                <p><input type="text" placeholder="Body Marks" name="bmarks" maxlength="100"></p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script src="{% static 'js/camera.js' %}"></script>
</body>
</html>

basic/templates/error.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Error 404 | Phoenix</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<style>
        * {
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
}

body {
  padding: 0;
  margin: 0;
}

#notfound {
  position: relative;
  height: 100vh;
}

#notfound .notfound {
  position: absolute;
  left: 50%;
  top: 50%;
  -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
}

.notfound {
  max-width: 520px;
  width: 100%;
  line-height: 1.4;
  text-align: center;
}

.notfound .notfound-404 {
  position: relative;
  height: 200px;
  margin: 0px auto 20px;
  z-index: -1;
}

.notfound .notfound-404 h1 {
  font-family: 'Montserrat', sans-serif;
  font-size: 236px;
  font-weight: 200;
  margin: 0px;
  color: #211b19;
  text-transform: uppercase;
  position: absolute;
  left: 50%;
  top: 50%;
  -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
}

.notfound .notfound-404 h2 {
  font-family: 'Montserrat', sans-serif;
  font-size: 28px;
  font-weight: 400;
  text-transform: uppercase;
  color: #211b19;
  background: #fff;
  padding: 10px 5px;
  margin: auto;
  display: inline-block;
  position: absolute;
  bottom: 0px;
  left: 0;
  right: 0;
}

.notfound a {
  font-family: 'Montserrat', sans-serif;
  display: inline-block;
  font-weight: 700;
  text-decoration: none;
  color: #fff;
  text-transform: uppercase;
  padding: 13px 23px;
  background: #ff6300;
  font-size: 18px;
  -webkit-transition: 0.2s all;
  transition: 0.2s all;
}

.notfound a:hover {
  color: #ff6300;
  background: #211b19;
}

@media only screen and (max-width: 767px) {
  .notfound .notfound-404 h1 {
    font-size: 148px;
  }
}

@media only screen and (max-width: 480px) {
  .notfound .notfound-404 {
    height: 148px;
    margin: 0px auto 10px;
  }
  .notfound .notfound-404 h1 {
    font-size: 86px;
  }
  .notfound .notfound-404 h2 {
    font-size: 16px;
  }
  .notfound a {
    padding: 7px 15px;
    font-size: 14px;
  }
}

    </style>

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Oops!</h1>
				<h2>404 - The Page can't be found</h2>
			</div>
			<a href="{% url 'home' %}">Go To Homepage</a>
		</div>
	</div>

</body>

</html>

basic/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <link rel="stylesheet" href="{% static 'styles/login.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">
</head>
<body style="overflow:hidden; height:100vh;">
<div class="wrapper" style="position:fixed; z-index:5;">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="{% url 'home' %}" method="post">
        {% csrf_token %}
        <h1>Login</h1>
        <div class="input-box">
            <input type="text" placeholder="Username" name="username" required>
            <i class='bx bxs-user'></i>
        </div>
        <div class="input-box">
            <input type="password" name="password" placeholder="Password" required>
            <i class='bx bxs-lock'></i>
        </div>
        <div class="remember-forgot">
            <label><input type="checkbox">Remember me</label>
            <a href="#">Forgot password?</a>
        </div>
        <button type="submit" class="btn">Login</button>
        <div class="register">
            <p>Don't have an account?
                <a href="">Register</a>
            </p>
        </div>
    </form>
</div>
</body>
</html>